### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by fleli723** [fleli723/sprint1v2#1]
- [x] Implement the DB.class.php and const.php files and use proper method calls to connect to the database
- [ ] replace mysqli statements with DB.class.php
- [ ] Change when to connect to DB
- [ ] Show generic error if connection to DB failed
- [ ] Implement now() for survey page entry to DB
- [ ] Change the prepared statement to DB.Class.php
- [ ] Change placement of "no results" on result.php
- [ ] Proper Album table formatting and styling
- [ ] Add duration (in seconds) to the Album table display
- [ ] PHP and JS validation and sanitization
- [ ] Pull Template.php and DB.class.php off canvas
- [ ] Possibly move const.php file to classes folder
- [ ] **Test site pages in PuTTY (php FILENAME)**
- [ ] **Require for db class not necessary in surveyy.php if database class is not used**
